### ISSUE TITLE
Update the submodule yolo_tracker to fix tut#6 error

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso-object-detection#120]
As reported by Pilar, tut#6 has some error with the yolo_trackker submodule 

![Image](https://user-images.githubusercontent.com/55268669/211770366-af947898-eedf-454c-9264-704594e3e8cc.png)

**Comment by jannesgg** [comment]
Submodule has been updated and error should be gone now.
