### ISSUE TITLE
readme: Add specifics for gpu usage on linux/mac for local computation

### ISSUE THREAD

**Issue by Diewertje11** [ocean-data-factory-sweden/kso-object-detection#194]
In the new readme that is added in commit 3ebc179facaed370b57cc6578a83debe6fa62643, there is maybe something missing for linux and mac for if you want to use a GPU locally. Can one of you check if you need to do something extra here? (you did need to do something on windows and that is in the readme)

**Comment by jannesgg** [comment]
@Diewertje11 Which part of the system requires the MIcrosoft Build Tools? I think that this will be quite different for each system and we do not necessarily need to provide this as part of the README. It might just be a general Python / GIT requirement. When users try to install various packages or build them, they will get a message saying to install Build Tools or XCode Command Line tools on Mac.

**Comment by jannesgg** [comment]
I would say so. If it's not something specific to KSO or our environment, I think is it fine to assume that they will find this on their own.
